#!/bin/bash

# Move to webapp dir
cd $(dirname "$(realpath -se "$0")")/..

# Run linter
yarn i18n

for LANG in src/translations/*.json; do
    jq --sort-keys . $LANG > $LANG.sorted && mv $LANG.sorted $LANG
done

CHANGED_FILES=$(git diff --name-only .)
if [ -z "$CHANGED_FILES" ]; then
    echo "No files were changed in these commits."
else
    echo "Following translations require update:"
    git diff src/translations
    exit 1
fi

echo "Verifying no empty strings"
PENDING_TRANSLATIONS=$(egrep '": ""' src/translations/*.json | wc -l)

if [ $PENDING_TRANSLATIONS -gt 0 ]; then
    echo "$PENDING_TRANSLATIONS pending translations in:"
    egrep '": ""' src/translations/*.json
    exit 1
fi

exit 0