#!/bin/bash

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

# Clear klear cache
chmod 777 /opt/irontec/ivozprovider/web/admin/application/cache
rm -fr /opt/irontec/ivozprovider/web/admin/application/cache/*

# Change invoice-template-tester dir owner
chown www-data:www-data /opt/irontec/ivozprovider/web/admin/public/invoice-template-tester

# Setup portal language
db_get ivozprovider/language
sed -i -r "s/(lang: ).*/\1 $RET/" /opt/irontec/ivozprovider/web/admin/application/configs/application.ini

:
