#!/bin/bash

#DEBHELPER#

# Add bashrc.d include on first install
if [ -z "$2" ]; then
    echo >> ~/.bashrc
    echo '# Include extra resources files' >> ~/.bashrc
    echo '[ -d ~/.bashrc.d ] && for RC_FILE in ~/.bashrc.d/*; do . $RC_FILE; done' >> ~/.bashrc
    echo >> ~/.bashrc
fi

# Create certificate links if required
[ ! -e /etc/ssl/certs/ivozprovider-portals.pem ]    && /bin/ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem   /etc/ssl/certs/ivozprovider-portals.pem
[ ! -e /etc/ssl/private/ivozprovider-portals.key ]  && /bin/ln -s /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/private/ivozprovider-portals.key
[ ! -e /etc/ssl/certs/yealink.crt ]     && /bin/ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem      /etc/ssl/certs/yealink.crt
[ ! -e /etc/ssl/private/yealink.key ]   && /bin/ln -s /etc/ssl/private/ssl-cert-snakeoil.key    /etc/ssl/private/yealink.key
[ ! -e /etc/ssl/certs/cisco.crt ]       && /bin/ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem      /etc/ssl/certs/cisco.crt
[ ! -e /etc/ssl/private/cisco.key ]     && /bin/ln -s /etc/ssl/private/ssl-cert-snakeoil.key    /etc/ssl/private/cisco.key

# Enable apache sites and modules
[ ! -L /etc/apache2/mods-enabled/headers.load ] && /usr/sbin/a2enmod headers
[ ! -L /etc/apache2/mods-enabled/rewrite.load ] && /usr/sbin/a2enmod rewrite
[ ! -L /etc/apache2/mods-enabled/ssl.load ] && /usr/sbin/a2enmod ssl
[ ! -L /etc/apache2/mods-enabled/mpm_prefork.load ] && /usr/sbin/a2enmod mpm_prefork
[   -L /etc/apache2/mods-enabled/mpm_event.load ] && /usr/sbin/a2dismod mpm_event
[   -L /etc/apache2/sites-enabled/000-default.conf ] && /usr/sbin/a2dissite 000-default
[ ! -L /etc/apache2/sites-enabled/020-ivozprovider-portals.conf ] && /usr/sbin/a2ensite 020-ivozprovider-portals.conf
[ ! -L /etc/apache2/sites-enabled/030-ivozprovider-prov.conf ] && /usr/sbin/a2ensite 030-ivozprovider-prov.conf

# Enable services
/bin/systemctl enable apache2
/bin/systemctl reload apache2

:
