#!/bin/bash

#DEBHELPER#

# Set current environment
export SYMFONY_ENV=prod

# Enable php environment variables
/bin/sed -i 's/variables_order = "GPCS"/variables_order = "EGPCS"/g' /etc/php/7.0/cli/php.ini

# Create project cache
cd /opt/irontec/ivozprovider/asterisk/agi

# Set proper var permissions
setfacl -dR -m u:www-data:rwX -m u:root:rwX var
setfacl  -R -m u:www-data:rwX -m u:root:rwX var

bin/console cache:clear --no-warmup -q -n

:
