DROP TABLE IF EXISTS `ParsedCDRs`;

CREATE TABLE `ParsedCDRs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `calldate` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'aleg timestamp',
  `type` varchar(256) DEFAULT NULL COMMENT 'Call type',
  `desc` varchar(256) DEFAULT NULL COMMENT 'Call description',
  `src` varchar(128) DEFAULT NULL COMMENT 'Caller',
  `src_dialed` varchar(128) DEFAULT NULL COMMENT 'Dialed Number',
  `src_duration` int(10) unsigned DEFAULT NULL COMMENT 'aleg call duration',
  `dst` varchar(128) DEFAULT NULL COMMENT 'Final Callee - bleg destination',
  `dst_src_cid` varchar(128) DEFAULT NULL COMMENT 'CallerID seen by call destination',
  `dst_duration` int(10) unsigned DEFAULT NULL COMMENT 'bleg call duration',
  `fw_desc` varchar(256) DEFAULT NULL COMMENT 'Call forwarding description',
  `ext_forwarder` varchar(32) DEFAULT NULL COMMENT 'aleg diversion',
  `int_forwarder` varchar(32) DEFAULT NULL COMMENT 'bleg diversion',
  `forward_to` varchar(32) DEFAULT NULL COMMENT 'Dialed number after forwarding',
  `aleg` varchar(128) DEFAULT NULL COMMENT 'aleg CallID',
  `bleg` varchar(128) DEFAULT NULL COMMENT 'bleg CallID',
  `billCallID` varchar(128) DEFAULT NULL COMMENT 'Billable leg CallID',
  `billDuration` int(10) unsigned DEFAULT NULL COMMENT 'Billable leg duration',
  `billDestination` varchar(128) DEFAULT NULL COMMENT 'Billable leg destination',
  `externallyRated` tinyint(1) DEFAULT '0' COMMENT '1 for billable calls billed elsewhere',
  `metered` tinyint(1) DEFAULT '0' COMMENT '1 for billable calls with price set',
  `meteringDate` datetime DEFAULT '0000-00-00 00:00:00',
  `pricingPlanId` int(10) unsigned DEFAULT NULL COMMENT 'Pricing plan used for setting price',
  `targetPatternId` int(10) unsigned DEFAULT NULL COMMENT 'Destination group for billable call',
  `price` decimal(10,3) DEFAULT NULL COMMENT 'Final price for billable call',
  `pricingPlanDetails` text,
  `invoiceId` int(10) unsigned DEFAULT NULL COMMENT 'Invoice for billable billed call',
  `peeringContractId` int(10) unsigned DEFAULT NULL COMMENT 'Billable call used Peering Contract',
  `companyId` int(10) unsigned DEFAULT NULL,
  `brandId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `brandId` (`brandId`),
  KEY `companyId` (`companyId`),
  KEY `pricingPlanId` (`pricingPlanId`),
  KEY `targetPatternId` (`targetPatternId`),
  KEY `invoiceId` (`invoiceId`),
  KEY `peeringContractId` (`peeringContractId`),
  CONSTRAINT `parsedCDRs_ibfk_1` FOREIGN KEY (`brandId`) REFERENCES `Brands` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_2` FOREIGN KEY (`companyId`) REFERENCES `Companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_3` FOREIGN KEY (`pricingPlanId`) REFERENCES `PricingPlans` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_4` FOREIGN KEY (`targetPatternId`) REFERENCES `TargetPatterns` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_5` FOREIGN KEY (`invoiceId`) REFERENCES `Invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_6` FOREIGN KEY (`peeringContractId`) REFERENCES `PeeringContracts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=56427 DEFAULT CHARSET=utf8 COMMENT='[entity]';
