DROP TABLE `ParsedCDRs`;

CREATE TABLE `ParsedCDRs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `statId` int(10) unsigned DEFAULT NULL,
  `xstatId` int(10) unsigned DEFAULT NULL,
  `statType` varchar(256) DEFAULT NULL,
  `initialLeg` varchar(128) DEFAULT NULL,
  `initialLegHash` varchar(128) DEFAULT NULL,
  `cid` varchar(128) DEFAULT NULL,
  `cidHash` varchar(128) DEFAULT NULL,
  `xcid` varchar(128) DEFAULT NULL,
  `xcidHash` varchar(128) DEFAULT NULL,
  `proxies` varchar(32) DEFAULT NULL,
  `type` varchar(32) DEFAULT NULL,
  `subtype` varchar(64) DEFAULT NULL,
  `calldate` timestamp NOT NULL,
  `duration` int(10) unsigned DEFAULT NULL,
  `xDuration` int(10) unsigned DEFAULT NULL,
  `aParty` varchar(128) DEFAULT NULL,
  `bParty` varchar(128) DEFAULT NULL,
  `caller` varchar(128) DEFAULT NULL,
  `callee` varchar(128) DEFAULT NULL,
  `xCaller` varchar(128) DEFAULT NULL,
  `xCallee` varchar(128) DEFAULT NULL,
  `initialReferrer` varchar(128) DEFAULT NULL,
  `referrer` varchar(128) DEFAULT NULL,
  `referee` varchar(128) DEFAULT NULL,
  `lastForwarder` varchar(32) DEFAULT NULL,
  `brandId` int(10) unsigned DEFAULT NULL,
  `companyId` int(10) unsigned DEFAULT NULL,
  `peeringContractId` int(10) unsigned DEFAULT NULL,
  `billCallID` varchar(128) DEFAULT NULL COMMENT 'Billable leg CallID',
  `billDuration` int(10) unsigned DEFAULT NULL COMMENT 'Billable leg duration',
  `billDestination` varchar(128) DEFAULT NULL COMMENT 'Billable leg destination',
  `externallyRated` tinyint(1) DEFAULT '0' COMMENT '1 for billable calls billed elsewhere',
  `metered` tinyint(1) DEFAULT '0' COMMENT '1 for billable calls with price set',
  `meteringDate` datetime DEFAULT '0000-00-00 00:00:00',
  `pricingPlanId` int(10) unsigned DEFAULT NULL COMMENT 'Pricing plan used for setting price',
  `targetPatternId` int(10) unsigned DEFAULT NULL COMMENT 'Destination group for billable call',
  `price` decimal(10,3) DEFAULT NULL COMMENT 'Final price for billable call',
  `pricingPlanDetails` text,
  `invoiceId` int(10) unsigned DEFAULT NULL COMMENT 'Invoice for billable billed call',
  PRIMARY KEY (`id`),
  UNIQUE KEY `cid` (`cid`),
  KEY `brandId` (`brandId`),
  KEY `companyId` (`companyId`),
  KEY `pricingPlanId` (`pricingPlanId`),
  KEY `targetPatternId` (`targetPatternId`),
  KEY `invoiceId` (`invoiceId`),
  KEY `peeringContractId` (`peeringContractId`),
  CONSTRAINT `parsedCDRs_ibfk_1` FOREIGN KEY (`brandId`) REFERENCES `Brands` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_2` FOREIGN KEY (`companyId`) REFERENCES `Companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_3` FOREIGN KEY (`pricingPlanId`) REFERENCES `PricingPlans` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_4` FOREIGN KEY (`targetPatternId`) REFERENCES `TargetPatterns` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_5` FOREIGN KEY (`invoiceId`) REFERENCES `Invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `parsedCDRs_ibfk_6` FOREIGN KEY (`peeringContractId`) REFERENCES `PeeringContracts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='[entity][rest]';

DELETE FROM `kam_acc_cdrs`;
DELETE FROM `kam_users_acc`;
DELETE FROM `kam_trunks_acc`;
DELETE FROM `kam_users_missed_calls`;
