ALTER TABLE `kam_acc_cdrs` ADD `externallyRated` tinyint(1) DEFAULT '0';
ALTER TABLE `kam_acc_cdrs` ADD `metered` tinyint(1) DEFAULT '0';
ALTER TABLE `kam_acc_cdrs` ADD `meteringDate` datetime DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `kam_acc_cdrs` ADD `pricingPlanId` int(10) unsigned DEFAULT NULL;
ALTER TABLE `kam_acc_cdrs` ADD `targetPatternId` int(10) unsigned DEFAULT NULL;
ALTER TABLE `kam_acc_cdrs` ADD `price` decimal(10,3) DEFAULT NULL;
ALTER TABLE `kam_acc_cdrs` ADD `pricingPlanDetails` text;
ALTER TABLE `kam_acc_cdrs` ADD `invoiceId` int(10) unsigned DEFAULT NULL;
ALTER TABLE `kam_acc_cdrs` ADD FOREIGN KEY (`pricingPlanId`) REFERENCES `PricingPlans` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `kam_acc_cdrs` ADD FOREIGN KEY (`targetPatternId`) REFERENCES `TargetPatterns` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `kam_acc_cdrs` ADD FOREIGN KEY (`invoiceId`) REFERENCES `Invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `ParsedCDRs` DROP FOREIGN KEY `parsedCDRs_ibfk_3`;
ALTER TABLE `ParsedCDRs` DROP FOREIGN KEY `parsedCDRs_ibfk_4`;
ALTER TABLE `ParsedCDRs` DROP FOREIGN KEY `parsedCDRs_ibfk_5`;
ALTER TABLE `ParsedCDRs` DROP KEY `pricingPlanId`;
ALTER TABLE `ParsedCDRs` DROP KEY `targetPatternId`;
ALTER TABLE `ParsedCDRs` DROP KEY `invoiceId`;
ALTER TABLE `ParsedCDRs` DROP `externallyRated`;
ALTER TABLE `ParsedCDRs` DROP `metered`;
ALTER TABLE `ParsedCDRs` DROP `meteringDate`;
ALTER TABLE `ParsedCDRs` DROP `pricingPlanId`;
ALTER TABLE `ParsedCDRs` DROP `targetPatternId`;
ALTER TABLE `ParsedCDRs` DROP `price`;
ALTER TABLE `ParsedCDRs` DROP `pricingPlanDetails`;
ALTER TABLE `ParsedCDRs` DROP `invoiceId`;
ALTER TABLE `ParsedCDRs` DROP `billCallID`;
ALTER TABLE `ParsedCDRs` DROP `billDuration`;
ALTER TABLE `ParsedCDRs` DROP `billDestination`;
ALTER TABLE `kam_acc_cdrs` COMMENT='[entity][rest]';
ALTER TABLE `kam_acc_cdrs` ADD `brandId` int(10) unsigned DEFAULT NULL AFTER `companyId`;
ALTER TABLE `kam_acc_cdrs` MODIFY `companyId` int(10) unsigned DEFAULT NULL;
ALTER TABLE `kam_acc_cdrs` MODIFY `peeringContractId` int(10) unsigned DEFAULT NULL;
ALTER TABLE `kam_acc_cdrs` ADD FOREIGN KEY (`peeringContractId`) REFERENCES `PeeringContracts` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
DELETE FROM kam_acc_cdrs;
ALTER TABLE `kam_acc_cdrs` ADD FOREIGN KEY (`brandId`) REFERENCES `Brands` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `kam_acc_cdrs` ADD FOREIGN KEY (`companyId`) REFERENCES `Companies` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;

