/*!40101 SET NAMES latin1 */;
/*!40101 SET character_set_client = latin1 */;
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AD';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AF';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='AG';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='AI';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AL';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='AO';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='AQ';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='AR';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='AS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='AU';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='AW';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AX';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BA';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BB';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BD';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BF';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BH';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BI';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BJ';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BL';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BN';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='BO';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='BR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BS';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BT';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='BV';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BW';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BY';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BZ';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='CA';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CD';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CG';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='CH';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CI';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='CK';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='CL';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CN';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='CO';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='CR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='CU';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CV';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CX';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CY';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='CZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='DE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='DJ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='DK';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='DM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='DO';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='DZ';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='EC';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='EE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='EG';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='EH';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ER';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='ES';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ET';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='FI';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='FJ';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='FK';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='FM';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='FO';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='FR';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GA';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GB';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GD';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='GE';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='GF';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GG';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GH';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GI';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GL';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GN';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GP';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GQ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GR';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='GS';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='GU';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GW';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='GY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='HK';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='HM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='HN';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='HR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='HT';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='HU';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='ID';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IL';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IN';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IO';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IQ';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IR';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IT';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='JE';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='JM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='JO';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='JP';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='KE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KH';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='KI';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='KM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='KN';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KP';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KR';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KW';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='KY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KZ';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='LA';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='LB';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='LC';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LI';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='LK';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='LR';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='LS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LT';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LU';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LV';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='LY';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MA';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MC';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MD';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='ME';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MG';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='MH';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MK';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ML';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MN';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MO';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='MP';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MQ';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MT';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MU';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MV';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MW';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MX';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MY';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MZ';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='NA';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='NE';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='NG';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='NI';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='NL';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='NO';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='NP';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NR';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NU';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NZ';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='OM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='PA';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='PE';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PF';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='PH';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='PK';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='PL';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='PM';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PN';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='PR';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='PS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='PT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PW';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='PY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='QA';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='RE';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='RO';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='RS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='RU';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='RW';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='SA';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='SB';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SD';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='SG';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SH';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SI';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SJ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SK';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SL';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SN';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SO';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='SR';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ST';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='SV';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='SY';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SZ';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='TC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TD';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='TF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TH';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TJ';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='TK';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TL';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TN';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='TO';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='TR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='TT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='TV';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TW';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='UA';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='UG';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='UM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='US';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='UY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='UZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='VA';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='VC';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='VE';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='VG';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='VI';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='VN';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='VU';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='WF';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='WS';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='YE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='YT';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ZA';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ZM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ZW';
UPDATE Countries SET zone_en='South america', zone_es='América del sur' WHERE code='BQ';
UPDATE Countries SET zone_en='South america', zone_es='América del sur' WHERE code='CW';
UPDATE Countries SET zone_en='Africa', zone_es='África' WHERE code='SS';
UPDATE Countries SET zone_en='North america', zone_es='América del norte' WHERE code='SX';

UPDATE Countries SET zone=NULL;
