/*!40101 SET NAMES utf8 */;
/*!40101 SET character_set_client = utf8 */;
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AD';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AF';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='AG';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='AI';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AL';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='AO';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='AQ';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='AR';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='AS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='AU';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='AW';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='AX';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='AZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BA';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BB';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BD';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BF';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BH';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BI';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BJ';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BL';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BN';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='BO';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='BR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BS';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='BT';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='BV';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='BW';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='BY';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='BZ';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='CA';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CD';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CG';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='CH';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CI';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='CK';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='CL';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CN';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='CO';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='CR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='CU';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='CV';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CX';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='CY';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='CZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='DE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='DJ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='DK';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='DM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='DO';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='DZ';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='EC';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='EE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='EG';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='EH';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ER';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='ES';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ET';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='FI';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='FJ';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='FK';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='FM';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='FO';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='FR';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GA';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GB';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GD';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='GE';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='GF';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GG';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GH';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GI';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GL';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GN';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GP';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GQ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='GR';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='GS';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='GT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='GU';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='GW';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='GY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='HK';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='HM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='HN';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='HR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='HT';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='HU';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='ID';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IL';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IN';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IO';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IQ';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='IR';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='IT';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='JE';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='JM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='JO';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='JP';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='KE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KH';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='KI';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='KM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='KN';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KP';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KR';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KW';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='KY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='KZ';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='LA';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='LB';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='LC';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LI';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='LK';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='LR';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='LS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LT';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LU';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='LV';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='LY';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MA';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MC';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MD';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='ME';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MG';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='MH';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MK';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ML';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MM';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MN';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MO';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='MP';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MQ';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='MT';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MU';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MV';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MW';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='MX';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='MY';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='MZ';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='NA';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='NE';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='NG';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='NI';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='NL';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='NO';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='NP';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NR';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NU';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='NZ';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='OM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='PA';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='PE';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PF';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='PH';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='PK';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='PL';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='PM';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PN';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='PR';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='PS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='PT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='PW';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='PY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='QA';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='RE';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='RO';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='RS';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='RU';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='RW';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='SA';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='SB';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SD';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SE';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='SG';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SH';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SI';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SJ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SK';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SL';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='SM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SN';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SO';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='SR';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ST';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='SV';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='SY';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='SZ';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='TC';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TD';
UPDATE Countries SET zone_es='Antártida', zone_en='Antarctica' WHERE code='TF';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TG';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TH';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TJ';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='TK';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TL';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TN';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='TO';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='TR';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='TT';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='TV';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='TW';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='TZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='UA';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='UG';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='UM';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='US';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='UY';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='UZ';
UPDATE Countries SET zone_es='Europa', zone_en='Europe' WHERE code='VA';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='VC';
UPDATE Countries SET zone_es='América del sur', zone_en='South america' WHERE code='VE';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='VG';
UPDATE Countries SET zone_es='América del norte', zone_en='North america' WHERE code='VI';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='VN';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='VU';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='WF';
UPDATE Countries SET zone_es='Oceanía', zone_en='Oceania' WHERE code='WS';
UPDATE Countries SET zone_es='Asia', zone_en='Asia' WHERE code='YE';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='YT';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ZA';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ZM';
UPDATE Countries SET zone_es='África', zone_en='Africa' WHERE code='ZW';
UPDATE Countries SET zone_en='South america', zone_es='América del sur' WHERE code='BQ';
UPDATE Countries SET zone_en='South america', zone_es='América del sur' WHERE code='CW';
UPDATE Countries SET zone_en='Africa', zone_es='África' WHERE code='SS';
UPDATE Countries SET zone_en='North america', zone_es='América del norte' WHERE code='SX';
UPDATE Countries SET zone=NULL;

UPDATE Countries SET name_es='Afganistán', name_en='Afghanistan', calling_code='93' WHERE code='AF';
UPDATE Countries SET name_es='Albania', name_en='Albania', calling_code='355' WHERE code='AL';
UPDATE Countries SET name_es='Alemania', name_en='Germany', calling_code='49' WHERE code='DE';
UPDATE Countries SET name_es='Algeria', name_en='Algeria', calling_code='213' WHERE code='DZ';
UPDATE Countries SET name_es='Andorra', name_en='Andorra', calling_code='376' WHERE code='AD';
UPDATE Countries SET name_es='Angola', name_en='Angola', calling_code='244' WHERE code='AO';
UPDATE Countries SET name_es='Anguila', name_en='Anguilla', calling_code='1264' WHERE code='AI';
UPDATE Countries SET name_es='Antártida', name_en='Antarctica', calling_code='672' WHERE code='AQ';
UPDATE Countries SET name_es='Antigua y Barbuda', name_en='Antigua and Barbuda', calling_code='1268' WHERE code='AG';
UPDATE Countries SET name_es='Antillas Neerlandesas', name_en='Netherlands Antilles', calling_code='599' WHERE code='AN';
UPDATE Countries SET name_es='Arabia Saudita', name_en='Saudi Arabia', calling_code='966' WHERE code='SA';
UPDATE Countries SET name_es='Argentina', name_en='Argentina', calling_code='54' WHERE code='AR';
UPDATE Countries SET name_es='Armenia', name_en='Armenia', calling_code='374' WHERE code='AM';
UPDATE Countries SET name_es='Aruba', name_en='Aruba', calling_code='297' WHERE code='AW';
UPDATE Countries SET name_es='Australia', name_en='Australia', calling_code='61' WHERE code='AU';
UPDATE Countries SET name_es='Austria', name_en='Austria', calling_code='43' WHERE code='AT';
UPDATE Countries SET name_es='Azerbayán', name_en='Azerbaijan', calling_code='994' WHERE code='AZ';
UPDATE Countries SET name_es='Bélgica', name_en='Belgium', calling_code='32' WHERE code='BE';
UPDATE Countries SET name_es='Bahamas', name_en='Bahamas', calling_code='1242' WHERE code='BS';
UPDATE Countries SET name_es='Bahrein', name_en='Bahrain', calling_code='973' WHERE code='BH';
UPDATE Countries SET name_es='Bangladesh', name_en='Bangladesh', calling_code='880' WHERE code='BD';
UPDATE Countries SET name_es='Barbados', name_en='Barbados', calling_code='1246' WHERE code='BB';
UPDATE Countries SET name_es='Belice', name_en='Belize', calling_code='501' WHERE code='BZ';
UPDATE Countries SET name_es='Benín', name_en='Benin', calling_code='229' WHERE code='BJ';
UPDATE Countries SET name_es='Bhután', name_en='Bhutan', calling_code='975' WHERE code='BT';
UPDATE Countries SET name_es='Bielorrusia', name_en='Belarus', calling_code='375' WHERE code='BY';
UPDATE Countries SET name_es='Birmania', name_en='Myanmar', calling_code='95' WHERE code='MM';
UPDATE Countries SET name_es='Bolivia', name_en='Bolivia', calling_code='591' WHERE code='BO';
UPDATE Countries SET name_es='Bosnia y Herzegovina', name_en='Bosnia and Herzegovina', calling_code='387' WHERE code='BA';
UPDATE Countries SET name_es='Botsuana', name_en='Botswana', calling_code='267' WHERE code='BW';
UPDATE Countries SET name_es='Brasil', name_en='Brazil', calling_code='55' WHERE code='BR';
UPDATE Countries SET name_es='Brunéi', name_en='Brunei', calling_code='673' WHERE code='BN';
UPDATE Countries SET name_es='Bulgaria', name_en='Bulgaria', calling_code='359' WHERE code='BG';
UPDATE Countries SET name_es='Burkina Faso', name_en='Burkina Faso', calling_code='226' WHERE code='BF';
UPDATE Countries SET name_es='Burundi', name_en='Burundi', calling_code='257' WHERE code='BI';
UPDATE Countries SET name_es='Cabo Verde', name_en='Cape Verde', calling_code='238' WHERE code='CV';
UPDATE Countries SET name_es='Camboya', name_en='Cambodia', calling_code='855' WHERE code='KH';
UPDATE Countries SET name_es='Camerún', name_en='Cameroon', calling_code='237' WHERE code='CM';
UPDATE Countries SET name_es='Canadá', name_en='Canada', calling_code='1' WHERE code='CA';
UPDATE Countries SET name_es='Chad', name_en='Chad', calling_code='235' WHERE code='TD';
UPDATE Countries SET name_es='Chile', name_en='Chile', calling_code='56' WHERE code='CL';
UPDATE Countries SET name_es='China', name_en='China', calling_code='86' WHERE code='CN';
UPDATE Countries SET name_es='Chipre', name_en='Cyprus', calling_code='357' WHERE code='CY';
UPDATE Countries SET name_es='Ciudad del Vaticano', name_en='Vatican City State', calling_code='39' WHERE code='VA';
UPDATE Countries SET name_es='Colombia', name_en='Colombia', calling_code='57' WHERE code='CO';
UPDATE Countries SET name_es='Comoras', name_en='Comoros', calling_code='269' WHERE code='KM';
UPDATE Countries SET name_es='Congo', name_en='Congo', calling_code='242' WHERE code='CG';
UPDATE Countries SET name_es='Congo', name_en='Congo', calling_code='243' WHERE code='CD';
UPDATE Countries SET name_es='Corea del Norte', name_en='North Korea', calling_code='850' WHERE code='KP';
UPDATE Countries SET name_es='Corea del Sur', name_en='South Korea', calling_code='82' WHERE code='KR';
UPDATE Countries SET name_es='Costa de Marfil', name_en='Ivory Coast', calling_code='225' WHERE code='CI';
UPDATE Countries SET name_es='Costa Rica', name_en='Costa Rica', calling_code='506' WHERE code='CR';
UPDATE Countries SET name_es='Croacia', name_en='Croatia', calling_code='385' WHERE code='HR';
UPDATE Countries SET name_es='Cuba', name_en='Cuba', calling_code='53' WHERE code='CU';
UPDATE Countries SET name_es='Dinamarca', name_en='Denmark', calling_code='45' WHERE code='DK';
UPDATE Countries SET name_es='Dominica', name_en='Dominica', calling_code='1767' WHERE code='DM';
UPDATE Countries SET name_es='Ecuador', name_en='Ecuador', calling_code='593' WHERE code='EC';
UPDATE Countries SET name_es='Egipto', name_en='Egypt', calling_code='20' WHERE code='EG';
UPDATE Countries SET name_es='El Salvador', name_en='El Salvador', calling_code='503' WHERE code='SV';
UPDATE Countries SET name_es='Emiratos Árabes Unidos', name_en='United Arab Emirates', calling_code='971' WHERE code='AE';
UPDATE Countries SET name_es='Eritrea', name_en='Eritrea', calling_code='291' WHERE code='ER';
UPDATE Countries SET name_es='Eslovaquia', name_en='Slovakia', calling_code='421' WHERE code='SK';
UPDATE Countries SET name_es='Eslovenia', name_en='Slovenia', calling_code='386' WHERE code='SI';
UPDATE Countries SET name_es='España', name_en='Spain', calling_code='34' WHERE code='ES';
UPDATE Countries SET name_es='Estados Unidos de América', name_en='United States of America', calling_code='1' WHERE code='US';
UPDATE Countries SET name_es='Estonia', name_en='Estonia', calling_code='372' WHERE code='EE';
UPDATE Countries SET name_es='Etiopía', name_en='Ethiopia', calling_code='251' WHERE code='ET';
UPDATE Countries SET name_es='Filipinas', name_en='Philippines', calling_code='63' WHERE code='PH';
UPDATE Countries SET name_es='Finlandia', name_en='Finland', calling_code='358' WHERE code='FI';
UPDATE Countries SET name_es='Fiyi', name_en='Fiji', calling_code='679' WHERE code='FJ';
UPDATE Countries SET name_es='Francia', name_en='France', calling_code='33' WHERE code='FR';
UPDATE Countries SET name_es='Gabón', name_en='Gabon', calling_code='241' WHERE code='GA';
UPDATE Countries SET name_es='Gambia', name_en='Gambia', calling_code='220' WHERE code='GM';
UPDATE Countries SET name_es='Georgia', name_en='Georgia', calling_code='995' WHERE code='GE';
UPDATE Countries SET name_es='Ghana', name_en='Ghana', calling_code='233' WHERE code='GH';
UPDATE Countries SET name_es='Gibraltar', name_en='Gibraltar', calling_code='350' WHERE code='GI';
UPDATE Countries SET name_es='Granada', name_en='Grenada', calling_code='1473' WHERE code='GD';
UPDATE Countries SET name_es='Grecia', name_en='Greece', calling_code='30' WHERE code='GR';
UPDATE Countries SET name_es='Groenlandia', name_en='Greenland', calling_code='299' WHERE code='GL';
UPDATE Countries SET name_es='Guadalupe', name_en='Guadeloupe', calling_code='590' WHERE code='GP';
UPDATE Countries SET name_es='Guam', name_en='Guam', calling_code='1671' WHERE code='GU';
UPDATE Countries SET name_es='Guatemala', name_en='Guatemala', calling_code='502' WHERE code='GT';
UPDATE Countries SET name_es='Guayana Francesa', name_en='French Guiana', calling_code='594' WHERE code='GF';
UPDATE Countries SET name_es='Guernsey', name_en='Guernsey', calling_code='44' WHERE code='GG';
UPDATE Countries SET name_es='Guinea', name_en='Guinea', calling_code='224' WHERE code='GN';
UPDATE Countries SET name_es='Guinea Ecuatorial', name_en='Equatorial Guinea', calling_code='240' WHERE code='GQ';
UPDATE Countries SET name_es='Guinea-Bissau', name_en='Guinea-Bissau', calling_code='245' WHERE code='GW';
UPDATE Countries SET name_es='Guyana', name_en='Guyana', calling_code='592' WHERE code='GY';
UPDATE Countries SET name_es='Haití', name_en='Haiti', calling_code='509' WHERE code='HT';
UPDATE Countries SET name_es='Honduras', name_en='Honduras', calling_code='504' WHERE code='HN';
UPDATE Countries SET name_es='Hong kong', name_en='Hong Kong', calling_code='852' WHERE code='HK';
UPDATE Countries SET name_es='Hungría', name_en='Hungary', calling_code='36' WHERE code='HU';
UPDATE Countries SET name_es='India', name_en='India', calling_code='91' WHERE code='IN';
UPDATE Countries SET name_es='Indonesia', name_en='Indonesia', calling_code='62' WHERE code='ID';
UPDATE Countries SET name_es='Irán', name_en='Iran', calling_code='98' WHERE code='IR';
UPDATE Countries SET name_es='Irak', name_en='Iraq', calling_code='964' WHERE code='IQ';
UPDATE Countries SET name_es='Irlanda', name_en='Ireland', calling_code='353' WHERE code='IE';
UPDATE Countries SET name_es='Isla Bouvet', name_en='Bouvet Island', calling_code='47' WHERE code='BV';
UPDATE Countries SET name_es='Isla de Man', name_en='Isle of Man', calling_code='44' WHERE code='IM';
UPDATE Countries SET name_es='Isla de Navidad', name_en='Christmas Island', calling_code='61' WHERE code='CX';
UPDATE Countries SET name_es='Isla Norfolk', name_en='Norfolk Island', calling_code='672' WHERE code='NF';
UPDATE Countries SET name_es='Islandia', name_en='Iceland', calling_code='354' WHERE code='IS';
UPDATE Countries SET name_es='Islas Bermudas', name_en='Bermuda Islands', calling_code='1441' WHERE code='BM';
UPDATE Countries SET name_es='Islas Caimán', name_en='Cayman Islands', calling_code='1345' WHERE code='KY';
UPDATE Countries SET name_es='Islas Cocos (Keeling)', name_en='Cocos (Keeling) Islands', calling_code='61' WHERE code='CC';
UPDATE Countries SET name_es='Islas Cook', name_en='Cook Islands', calling_code='682' WHERE code='CK';
UPDATE Countries SET name_es='Islas de Åland', name_en='Åland Islands', calling_code='358' WHERE code='AX';
UPDATE Countries SET name_es='Islas Feroe', name_en='Faroe Islands', calling_code='298' WHERE code='FO';
UPDATE Countries SET name_es='Islas Georgias del Sur y Sandwich del Sur', name_en='South Georgia and the South Sandwich Islands', calling_code='500' WHERE code='GS';
UPDATE Countries SET name_es='Islas Heard y McDonald', name_en='Heard Island and McDonald Islands', calling_code='672' WHERE code='HM';
UPDATE Countries SET name_es='Islas Maldivas', name_en='Maldives', calling_code='960' WHERE code='MV';
UPDATE Countries SET name_es='Islas Malvinas', name_en='Falkland Islands (Malvinas)', calling_code='500' WHERE code='FK';
UPDATE Countries SET name_es='Islas Marianas del Norte', name_en='Northern Mariana Islands', calling_code='1670' WHERE code='MP';
UPDATE Countries SET name_es='Islas Marshall', name_en='Marshall Islands', calling_code='692' WHERE code='MH';
UPDATE Countries SET name_es='Islas Pitcairn', name_en='Pitcairn Islands', calling_code='870' WHERE code='PN';
UPDATE Countries SET name_es='Islas Salomón', name_en='Solomon Islands', calling_code='677' WHERE code='SB';
UPDATE Countries SET name_es='Islas Turcas y Caicos', name_en='Turks and Caicos Islands', calling_code='1649' WHERE code='TC';
UPDATE Countries SET name_es='Islas Ultramarinas Menores de Estados Unidos', name_en='United States Minor Outlying Islands', calling_code='1' WHERE code='UM';
UPDATE Countries SET name_es='Islas Vírgenes Británicas', name_en='Virgin Islands', calling_code='1284' WHERE code='VG';
UPDATE Countries SET name_es='Islas Vírgenes de los Estados Unidos', name_en='United States Virgin Islands', calling_code='1340' WHERE code='VI';
UPDATE Countries SET name_es='Israel', name_en='Israel', calling_code='972' WHERE code='IL';
UPDATE Countries SET name_es='Italia', name_en='Italy', calling_code='39' WHERE code='IT';
UPDATE Countries SET name_es='Jamaica', name_en='Jamaica', calling_code='1876' WHERE code='JM';
UPDATE Countries SET name_es='Japón', name_en='Japan', calling_code='81' WHERE code='JP';
UPDATE Countries SET name_es='Jersey', name_en='Jersey', calling_code='44' WHERE code='JE';
UPDATE Countries SET name_es='Jordania', name_en='Jordan', calling_code='962' WHERE code='JO';
UPDATE Countries SET name_es='Kazajistán', name_en='Kazakhstan', calling_code='7' WHERE code='KZ';
UPDATE Countries SET name_es='Kenia', name_en='Kenya', calling_code='254' WHERE code='KE';
UPDATE Countries SET name_es='Kirgizstán', name_en='Kyrgyzstan', calling_code='996' WHERE code='KG';
UPDATE Countries SET name_es='Kiribati', name_en='Kiribati', calling_code='686' WHERE code='KI';
UPDATE Countries SET name_es='Kuwait', name_en='Kuwait', calling_code='965' WHERE code='KW';
UPDATE Countries SET name_es='Líbano', name_en='Lebanon', calling_code='961' WHERE code='LB';
UPDATE Countries SET name_es='Laos', name_en='Laos', calling_code='856' WHERE code='LA';
UPDATE Countries SET name_es='Lesoto', name_en='Lesotho', calling_code='266' WHERE code='LS';
UPDATE Countries SET name_es='Letonia', name_en='Latvia', calling_code='371' WHERE code='LV';
UPDATE Countries SET name_es='Liberia', name_en='Liberia', calling_code='231' WHERE code='LR';
UPDATE Countries SET name_es='Libia', name_en='Libya', calling_code='218' WHERE code='LY';
UPDATE Countries SET name_es='Liechtenstein', name_en='Liechtenstein', calling_code='423' WHERE code='LI';
UPDATE Countries SET name_es='Lituania', name_en='Lithuania', calling_code='370' WHERE code='LT';
UPDATE Countries SET name_es='Luxemburgo', name_en='Luxembourg', calling_code='352' WHERE code='LU';
UPDATE Countries SET name_es='México', name_en='Mexico', calling_code='52' WHERE code='MX';
UPDATE Countries SET name_es='Mónaco', name_en='Monaco', calling_code='377' WHERE code='MC';
UPDATE Countries SET name_es='Macao', name_en='Macao', calling_code='853' WHERE code='MO';
UPDATE Countries SET name_es='Macedônia', name_en='Macedonia', calling_code='389' WHERE code='MK';
UPDATE Countries SET name_es='Madagascar', name_en='Madagascar', calling_code='261' WHERE code='MG';
UPDATE Countries SET name_es='Malasia', name_en='Malaysia', calling_code='60' WHERE code='MY';
UPDATE Countries SET name_es='Malawi', name_en='Malawi', calling_code='265' WHERE code='MW';
UPDATE Countries SET name_es='Mali', name_en='Mali', calling_code='223' WHERE code='ML';
UPDATE Countries SET name_es='Malta', name_en='Malta', calling_code='356' WHERE code='MT';
UPDATE Countries SET name_es='Marruecos', name_en='Morocco', calling_code='212' WHERE code='MA';
UPDATE Countries SET name_es='Martinica', name_en='Martinique', calling_code='596' WHERE code='MQ';
UPDATE Countries SET name_es='Mauricio', name_en='Mauritius', calling_code='230' WHERE code='MU';
UPDATE Countries SET name_es='Mauritania', name_en='Mauritania', calling_code='222' WHERE code='MR';
UPDATE Countries SET name_es='Mayotte', name_en='Mayotte', calling_code='262' WHERE code='YT';
UPDATE Countries SET name_es='Micronesia', name_en='Estados Federados de', calling_code='691' WHERE code='FM';
UPDATE Countries SET name_es='Moldavia', name_en='Moldova', calling_code='373' WHERE code='MD';
UPDATE Countries SET name_es='Mongolia', name_en='Mongolia', calling_code='976' WHERE code='MN';
UPDATE Countries SET name_es='Montenegro', name_en='Montenegro', calling_code='382' WHERE code='ME';
UPDATE Countries SET name_es='Montserrat', name_en='Montserrat', calling_code='1664' WHERE code='MS';
UPDATE Countries SET name_es='Mozambique', name_en='Mozambique', calling_code='258' WHERE code='MZ';
UPDATE Countries SET name_es='Namibia', name_en='Namibia', calling_code='264' WHERE code='NA';
UPDATE Countries SET name_es='Nauru', name_en='Nauru', calling_code='674' WHERE code='NR';
UPDATE Countries SET name_es='Nepal', name_en='Nepal', calling_code='977' WHERE code='NP';
UPDATE Countries SET name_es='Nicaragua', name_en='Nicaragua', calling_code='505' WHERE code='NI';
UPDATE Countries SET name_es='Niger', name_en='Niger', calling_code='227' WHERE code='NE';
UPDATE Countries SET name_es='Nigeria', name_en='Nigeria', calling_code='234' WHERE code='NG';
UPDATE Countries SET name_es='Niue', name_en='Niue', calling_code='683' WHERE code='NU';
UPDATE Countries SET name_es='Noruega', name_en='Norway', calling_code='47' WHERE code='NO';
UPDATE Countries SET name_es='Nueva Caledonia', name_en='New Caledonia', calling_code='687' WHERE code='NC';
UPDATE Countries SET name_es='Nueva Zelanda', name_en='New Zealand', calling_code='64' WHERE code='NZ';
UPDATE Countries SET name_es='Omán', name_en='Oman', calling_code='968' WHERE code='OM';
UPDATE Countries SET name_es='Países Bajos', name_en='Netherlands', calling_code='31' WHERE code='NL';
UPDATE Countries SET name_es='Pakistán', name_en='Pakistan', calling_code='92' WHERE code='PK';
UPDATE Countries SET name_es='Palau', name_en='Palau', calling_code='680' WHERE code='PW';
UPDATE Countries SET name_es='Palestina', name_en='Palestine', calling_code='970' WHERE code='PS';
UPDATE Countries SET name_es='Panamá', name_en='Panama', calling_code='507' WHERE code='PA';
UPDATE Countries SET name_es='Papúa Nueva Guinea', name_en='Papua New Guinea', calling_code='675' WHERE code='PG';
UPDATE Countries SET name_es='Paraguay', name_en='Paraguay', calling_code='595' WHERE code='PY';
UPDATE Countries SET name_es='Perú', name_en='Peru', calling_code='51' WHERE code='PE';
UPDATE Countries SET name_es='Polinesia Francesa', name_en='French Polynesia', calling_code='689' WHERE code='PF';
UPDATE Countries SET name_es='Polonia', name_en='Poland', calling_code='48' WHERE code='PL';
UPDATE Countries SET name_es='Portugal', name_en='Portugal', calling_code='351' WHERE code='PT';
UPDATE Countries SET name_es='Puerto Rico', name_en='Puerto Rico', calling_code='1' WHERE code='PR';
UPDATE Countries SET name_es='Qatar', name_en='Qatar', calling_code='974' WHERE code='QA';
UPDATE Countries SET name_es='Reino Unido', name_en='United Kingdom', calling_code='44' WHERE code='GB';
UPDATE Countries SET name_es='República Centroafricana', name_en='Central African Republic', calling_code='236' WHERE code='CF';
UPDATE Countries SET name_es='República Checa', name_en='Czech Republic', calling_code='420' WHERE code='CZ';
UPDATE Countries SET name_es='República Dominicana', name_en='Dominican Republic', calling_code='1809' WHERE code='DO';
UPDATE Countries SET name_es='Reunión', name_en='Réunion', calling_code='262' WHERE code='RE';
UPDATE Countries SET name_es='Ruanda', name_en='Rwanda', calling_code='250' WHERE code='RW';
UPDATE Countries SET name_es='Rumanía', name_en='Romania', calling_code='40' WHERE code='RO';
UPDATE Countries SET name_es='Rusia', name_en='Russia', calling_code='7' WHERE code='RU';
UPDATE Countries SET name_es='Sahara Occidental', name_en='Western Sahara', calling_code='212' WHERE code='EH';
UPDATE Countries SET name_es='Samoa', name_en='Samoa', calling_code='685' WHERE code='WS';
UPDATE Countries SET name_es='Samoa Americana', name_en='American Samoa', calling_code='1684' WHERE code='AS';
UPDATE Countries SET name_es='San Bartolomé', name_en='Saint Barthélemy', calling_code='590' WHERE code='BL';
UPDATE Countries SET name_es='San Cristóbal y Nieves', name_en='Saint Kitts and Nevis', calling_code='1869' WHERE code='KN';
UPDATE Countries SET name_es='San Marino', name_en='San Marino', calling_code='378' WHERE code='SM';
UPDATE Countries SET name_es='San Martín (Francia)', name_en='Saint Martin (French part)', calling_code='1599' WHERE code='MF';
UPDATE Countries SET name_es='San Pedro y Miquelón', name_en='Saint Pierre and Miquelon', calling_code='508' WHERE code='PM';
UPDATE Countries SET name_es='San Vicente y las Granadinas', name_en='Saint Vincent and the Grenadines', calling_code='1784' WHERE code='VC';
UPDATE Countries SET name_es='Santa Elena', name_en='Ascensión y Tristán de Acuña', calling_code='290' WHERE code='SH';
UPDATE Countries SET name_es='Santa Lucía', name_en='Saint Lucia', calling_code='1758' WHERE code='LC';
UPDATE Countries SET name_es='Santo Tomé y Príncipe', name_en='Sao Tome and Principe', calling_code='239' WHERE code='ST';
UPDATE Countries SET name_es='Senegal', name_en='Senegal', calling_code='221' WHERE code='SN';
UPDATE Countries SET name_es='Serbia', name_en='Serbia', calling_code='381' WHERE code='RS';
UPDATE Countries SET name_es='Seychelles', name_en='Seychelles', calling_code='248' WHERE code='SC';
UPDATE Countries SET name_es='Sierra Leona', name_en='Sierra Leone', calling_code='232' WHERE code='SL';
UPDATE Countries SET name_es='Singapur', name_en='Singapore', calling_code='65' WHERE code='SG';
UPDATE Countries SET name_es='Siria', name_en='Syria', calling_code='963' WHERE code='SY';
UPDATE Countries SET name_es='Somalia', name_en='Somalia', calling_code='252' WHERE code='SO';
UPDATE Countries SET name_es='Sri lanka', name_en='Sri Lanka', calling_code='94' WHERE code='LK';
UPDATE Countries SET name_es='Sudáfrica', name_en='South Africa', calling_code='27' WHERE code='ZA';
UPDATE Countries SET name_es='Sudán', name_en='Sudan', calling_code='249' WHERE code='SD';
UPDATE Countries SET name_es='Suecia', name_en='Sweden', calling_code='46' WHERE code='SE';
UPDATE Countries SET name_es='Suiza', name_en='Switzerland', calling_code='41' WHERE code='CH';
UPDATE Countries SET name_es='Surinám', name_en='Suriname', calling_code='597' WHERE code='SR';
UPDATE Countries SET name_es='Svalbard y Jan Mayen', name_en='Svalbard and Jan Mayen', calling_code='47' WHERE code='SJ';
UPDATE Countries SET name_es='Swazilandia', name_en='Swaziland', calling_code='268' WHERE code='SZ';
UPDATE Countries SET name_es='Tadjikistán', name_en='Tajikistan', calling_code='992' WHERE code='TJ';
UPDATE Countries SET name_es='Tailandia', name_en='Thailand', calling_code='66' WHERE code='TH';
UPDATE Countries SET name_es='Taiwán', name_en='Taiwan', calling_code='886' WHERE code='TW';
UPDATE Countries SET name_es='Tanzania', name_en='Tanzania', calling_code='255' WHERE code='TZ';
UPDATE Countries SET name_es='Territorio Británico del Océano Índico', name_en='British Indian Ocean Territory', calling_code='246' WHERE code='IO';
UPDATE Countries SET name_es='Territorios Australes y Antárticas Franceses', name_en='French Southern Territories', calling_code='262' WHERE code='TF';
UPDATE Countries SET name_es='Timor Oriental', name_en='East Timor', calling_code='670' WHERE code='TL';
UPDATE Countries SET name_es='Togo', name_en='Togo', calling_code='228' WHERE code='TG';
UPDATE Countries SET name_es='Tokelau', name_en='Tokelau', calling_code='690' WHERE code='TK';
UPDATE Countries SET name_es='Tonga', name_en='Tonga', calling_code='676' WHERE code='TO';
UPDATE Countries SET name_es='Trinidad y Tobago', name_en='Trinidad and Tobago', calling_code='1868' WHERE code='TT';
UPDATE Countries SET name_es='Tunez', name_en='Tunisia', calling_code='216' WHERE code='TN';
UPDATE Countries SET name_es='Turkmenistán', name_en='Turkmenistan', calling_code='993' WHERE code='TM';
UPDATE Countries SET name_es='Turquía', name_en='Turkey', calling_code='90' WHERE code='TR';
UPDATE Countries SET name_es='Tuvalu', name_en='Tuvalu', calling_code='688' WHERE code='TV';
UPDATE Countries SET name_es='Ucrania', name_en='Ukraine', calling_code='380' WHERE code='UA';
UPDATE Countries SET name_es='Uganda', name_en='Uganda', calling_code='256' WHERE code='UG';
UPDATE Countries SET name_es='Uruguay', name_en='Uruguay', calling_code='598' WHERE code='UY';
UPDATE Countries SET name_es='Uzbekistán', name_en='Uzbekistan', calling_code='998' WHERE code='UZ';
UPDATE Countries SET name_es='Vanuatu', name_en='Vanuatu', calling_code='678' WHERE code='VU';
UPDATE Countries SET name_es='Venezuela', name_en='Venezuela', calling_code='58' WHERE code='VE';
UPDATE Countries SET name_es='Vietnam', name_en='Vietnam', calling_code='84' WHERE code='VN';
UPDATE Countries SET name_es='Wallis y Futuna', name_en='Wallis and Futuna', calling_code='681' WHERE code='WF';
UPDATE Countries SET name_es='Yemen', name_en='Yemen', calling_code='967' WHERE code='YE';
UPDATE Countries SET name_es='Yibuti', name_en='Djibouti', calling_code='253' WHERE code='DJ';
UPDATE Countries SET name_es='Zambia', name_en='Zambia', calling_code='260' WHERE code='ZM';
UPDATE Countries SET name_es='Zimbabue', name_en='Zimbabwe', calling_code='263' WHERE code='ZW';
UPDATE Countries SET name_en='Curaçao', name_es='Curaçao' WHERE code='CW';
UPDATE Countries SET name_es='Sudán del Sur' WHERE code='SS';
UPDATE Countries SET name_es='Sint Maarten (parte neerlandesa)' WHERE code='SX';
