#!/bin/bash
# This script does nothing, only echoes useful mysql queries ;)

PROV_FOLDER=/opt/irontec/ivozprovider/portals/templates/provisioning
MYSQL_FOLDER=/var/lib/mysql-files/prov

function propose_queries {
    pushd $MYSQL_FOLDER &> /dev/null

    for file in `ls -1`; do
        if [[ $file =~ "generic" ]]; then
            echo "UPDATE TerminalModels SET genericTemplate=LOAD_FILE('$MYSQL_FOLDER/$file') WHERE '$file' REGEXP iden AND id > 1;"
        else
            echo "UPDATE TerminalModels SET specificTemplate=LOAD_FILE('$MYSQL_FOLDER/$file') WHERE '$file' REGEXP iden AND id > 1;"
        fi
    done

    popd &> /dev/null
}

function copy_templates {
    if [ -d $MYSQL_FOLDER ]; then
        rm -rf $MYSQL_FOLDER
    fi

    mkdir -p $MYSQL_FOLDER

    find $PROV_FOLDER -type f -exec cp {} $MYSQL_FOLDER \;
}

if [ "$#" -ne 0 ]; then
    echo -e "\e[31mNo arguments needed\e[0m"
    exit 1
fi

copy_templates
echo -e "\e[32mChoose queries or run them all:\e[0m\n"
propose_queries

echo -e "\n\e[33mDelete $MYSQL_FOLDER after running queries ;)\e[0m"
echo "rm -rf $MYSQL_FOLDER"

exit 0

